name: Regression suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '25 15 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and generate report
        run: |
          mkdir -p reports
          pytest --html=reports/report.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with: 
          name: pytest-report
          path: reports/report.html 
