name: Regression_suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run tests
        run: |
          pytest -s --html=report.html --self-contained-html  # Fixed flag typo (self-contained-html)

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: report.html
